# PREREQUISITES: 
# 1. Add secrets to this repo called DEV_CREDENTIALS, TEST_CREDENTIALS, and
#    PROD_CREDENTIALS. Each secret should be formatted like this:
#    {
#      "clientId": "...",
#      "clientSecret": "...",
#      "tenantId": "..."
#    }

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
        - DEV
        - TEST
        - PROD
        default: DEV

name: Deploy code to an environment (manual trigger)

env:
  DEV_URL: https://adb-2942084783280094.14.azuredatabricks.net
  TEST_URL: https://adb-6989291269021872.12.azuredatabricks.net
  PROD_URL: https://adb-5328330755793276.16.azuredatabricks.net

jobs:
  deploy_code:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Tell Github a deployment is happening
      uses: octokit/request-action@v2.1.0
      id: create_deployment
      with:
        token: ${{ github.token }}
        route: POST /repos/{repository}/deployments
        repository: ${{ github.repository }}
