# PREREQUISITES: 
# 1. Add secrets to this repo called DEV_CREDENTIALS, TEST_CREDENTIALS, and
#    PROD_CREDENTIALS. Each secret should be formatted like this:
#    {
#      "clientId": "...",
#      "clientSecret": "...",
#      "tenantId": "..."
#    }

on:
  workflow_dispatch

name: Deploy code to an environment (manual trigger)

env:
  DEV_URL: https://adb-2942084783280094.14.azuredatabricks.net
  TEST_URL: https://adb-6989291269021872.12.azuredatabricks.net
  PROD_URL: https://adb-5328330755793276.16.azuredatabricks.net

jobs:
  deploy_code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The value of github.token is: ${{ github.token }}"
      - run: echo "The value of github.repository is: ${{ github.repository }}"
      - run: echo "The value of github.ref is: ${{ github.ref }}"
      - run: echo "The value of github.ref_name is: ${{ github.ref_name }}"
      - run: echo "The value of github.run_id is: ${{ github.run_id }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
